using Content.Client.UserInterface;
using Content.Shared._RMC.Vendors;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RMC.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultWindow
{
    private enum VendorPage
    {
        Allocation,
        SharedEquipment,
    }

    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IGameTiming _timing = default!;

    public event Action<int, int>? OnVend;
    public event Action? OnReplenishHeld;
    public event Action? OnStoreHeld;
    public event Action<NetEntity>? OnWithdrawStored;

    private SpriteSystem _sprites = default!;
    private CMAutomatedVendorState? _state;
    private VendorPage _activePage;
    private string? _allocationCategory;
    private string? _sharedCategory;
    private readonly Dictionary<string, bool> _allocationExpanded = new();

    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();
        SearchBar.OnTextChanged += _ => Rebuild();
    }

    public void UpdateState(CMAutomatedVendorState state)
    {
        _state = state;
        Title = state.VendorTitle;
        _allocationCategory = EnsureCategory(_allocationCategory, GetAllocationCategories(state));
        _sharedCategory = EnsureCategory(_sharedCategory, GetSharedCategories(state));
        Rebuild();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_state != null)
            UpdateResupplyStatus(_state);
    }

    private void Rebuild()
    {
        if (_state is not { } state)
            return;

        PageButtons.RemoveAllChildren();
        CategoryButtons.RemoveAllChildren();
        Sections.RemoveAllChildren();
        ActionButtons.RemoveAllChildren();

        PointsLabel.Text = $"Allocation points: {state.Points}";
        AddPageButtons();

        if (_activePage == VendorPage.Allocation)
        {
            AddCategoryButtons(state);
            AddAllocationContent(state);
        }
        else
        {
            AddSharedCategoryButtons(state);
            AddSharedEquipmentContent(state);
        }

        AddActionButtons(state);
        UpdateResupplyStatus(state);
    }

    private void AddPageButtons()
    {
        if (_state is not { } state)
            return;

        PageButtons.AddChild(CreateTabButton("Allocation", _activePage == VendorPage.Allocation, () =>
        {
            _activePage = VendorPage.Allocation;
            Rebuild();
        }));
        PageButtons.AddChild(CreateTabButton($"{state.DepartmentName} shared equipment", _activePage == VendorPage.SharedEquipment, () =>
        {
            _activePage = VendorPage.SharedEquipment;
            Rebuild();
        }));
    }

    private void AddCategoryButtons(CMAutomatedVendorState state)
    {
        foreach (var category in GetAllocationCategories(state))
        {
            var count = state.Sections.Sum(section => section.Entries.Count(entry =>
                entry.Category.Equals(category, StringComparison.OrdinalIgnoreCase)));
            var captured = category;
            CategoryButtons.AddChild(CreateTabButton($"{category} ({count})",
                category.Equals(_allocationCategory, StringComparison.OrdinalIgnoreCase), () =>
            {
                _allocationCategory = captured;
                Rebuild();
            }));
        }
    }

    private void AddAllocationContent(CMAutomatedVendorState state)
    {
        var search = SearchBar.Text.Trim();
        var hasResults = false;

        for (var sectionIndex = 0; sectionIndex < state.Sections.Count; sectionIndex++)
        {
            var section = state.Sections[sectionIndex];
            var entries = section.Entries
                .Select((entry, entryIndex) => (entry, entryIndex))
                .Where(pair => MatchesAllocationFilter(pair.entry, search))
                .ToList();
            if (entries.Count == 0)
                continue;

            hasResults = true;
            var entryList = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 5,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            foreach (var (entry, entryIndex) in entries)
                entryList.AddChild(CreateAllocationEntry(state, section, entry, sectionIndex, entryIndex));

            var remaining = section.Choices is { } choices
                ? $" — CHOOSE {Math.Max(0, choices - section.Purchases)}"
                : string.Empty;
            var heading = new CollapsibleHeading($"{WithoutTierPrefix(section.Name).ToUpperInvariant()}{remaining}") { HorizontalExpand = true };
            heading.Label.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;
            var body = new CollapsibleBody { HorizontalExpand = true, Children = { entryList } };
            var collapsible = new Collapsible(heading, body)
            {
                HorizontalExpand = true,
                BodyVisible = _allocationExpanded.TryGetValue(section.Name, out var expanded) ? expanded : true,
            };
            heading.OnToggled += args => _allocationExpanded[section.Name] = args.Pressed;
            Sections.AddChild(collapsible);
        }

        if (!hasResults)
            AddEmptyMessage(string.IsNullOrWhiteSpace(search) ? "No equipment is assigned to this category." : "No equipment matches your search.");
    }

    private void AddSharedCategoryButtons(CMAutomatedVendorState state)
    {
        foreach (var category in GetSharedCategories(state))
        {
            var count = state.StoredItems.Count(item =>
                item.Category.Equals(category, StringComparison.OrdinalIgnoreCase));
            var captured = category;
            CategoryButtons.AddChild(CreateTabButton($"{category} ({count})",
                category.Equals(_sharedCategory, StringComparison.OrdinalIgnoreCase), () =>
            {
                _sharedCategory = captured;
                Rebuild();
            }));
        }
    }

    private bool MatchesAllocationFilter(CMVendorEntryState entry, string search)
    {
        if (!string.IsNullOrWhiteSpace(search))
        {
            var name = ResolvePrototype(entry.Name, entry.Id).Name;
            return name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                   entry.Category.Contains(search, StringComparison.OrdinalIgnoreCase);
        }

        return entry.Category.Equals(_allocationCategory, StringComparison.OrdinalIgnoreCase);
    }

    private Control CreateAllocationEntry(
        CMAutomatedVendorState state,
        CMVendorSectionState section,
        CMVendorEntryState entry,
        int sectionIndex,
        int entryIndex)
    {
        var prototype = ResolvePrototype(entry.Name, entry.Id);
        var disabledReason = GetDisabledReason(state, section, entry);
        var stock = entry.Amount is { } amount
            ? entry.MaxAmount is { } maximum ? $"Stock {amount}/{maximum}" : $"Stock {amount}"
            : "Unlimited stock";
        var cost = entry.Points is { } points ? $" • {points} point{(points == 1 ? string.Empty : "s")}" : string.Empty;
        var authority = entry.RequiredJob ?? WithoutTierPrefix(entry.RequiredAuthority ?? "Rank restricted");

        return CreateEntryRow(
            prototype.Name,
            prototype.Description,
            entry.Id,
            $"{stock}{cost} • {authority}",
            disabledReason,
            "ISSUE",
            () => OnVend?.Invoke(sectionIndex, entryIndex));
    }

    private static string? GetDisabledReason(
        CMAutomatedVendorState state,
        CMVendorSectionState section,
        CMVendorEntryState entry)
    {
        if (entry.Amount is <= 0)
            return "Out of stock";
        if (!entry.HasRequiredJob)
            return $"Requires {entry.RequiredJob ?? "another assignment"}";
        if (!entry.HasAuthority)
            return $"Requires {WithoutTierPrefix(entry.RequiredAuthority ?? "a higher rank")}";
        if (section.Choices is { } choices && section.Purchases >= choices)
            return "Allocation exhausted";
        if (entry.Points is { } cost && cost > state.Points)
            return "Not enough points";
        return null;
    }

    private void AddSharedEquipmentContent(CMAutomatedVendorState state)
    {
        Sections.AddChild(new Label
        {
            Text = "Shared equipment is physical department storage; item condition and contents are preserved.",
            ModulateSelfOverride = Color.LightGray,
            Margin = new Thickness(4, 0, 4, 4),
        });

        var search = SearchBar.Text.Trim();
        var stored = state.StoredItems
            .Where(item => !string.IsNullOrWhiteSpace(search)
                ? ResolvePrototype(item.Name, item.Id).Name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                  item.Category.Contains(search, StringComparison.OrdinalIgnoreCase)
                : item.Category.Equals(_sharedCategory, StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (stored.Count == 0)
        {
            AddEmptyMessage(string.IsNullOrWhiteSpace(search)
                ? state.StoredItems.Count == 0
                    ? $"No shared equipment is stored for the {state.DepartmentName}."
                    : "No stored equipment is assigned to this category."
                : "No stored equipment matches your search.");
            return;
        }

        foreach (var entry in stored)
        {
            var prototype = ResolvePrototype(entry.Name, entry.Id);
            Sections.AddChild(CreateEntryRow(
                prototype.Name,
                prototype.Description,
                entry.Id,
                entry.Category,
                null,
                "WITHDRAW",
                () => OnWithdrawStored?.Invoke(entry.Entity)));
        }
    }

    private void AddActionButtons(CMAutomatedVendorState state)
    {
        if (state.CanReplenish)
        {
            var replenish = new Button
            {
                Text = $"Contribute held {state.ReplenishmentPrompt} ({state.ReplenishmentPoints} resupply points)",
                HorizontalExpand = true,
                ToolTip = "Authorized requisition staff only. Currency funds replacement shipments for depleted allocations.",
            };
            replenish.OnPressed += _ => OnReplenishHeld?.Invoke();
            ActionButtons.AddChild(replenish);
        }

        if (_activePage == VendorPage.SharedEquipment && state.CanStoreEquipment)
        {
            var store = new Button
            {
                Text = $"Store held equipment for the {state.DepartmentName}",
                HorizontalExpand = true,
            };
            store.OnPressed += _ => OnStoreHeld?.Invoke();
            ActionButtons.AddChild(store);
        }
    }

    private void UpdateResupplyStatus(CMAutomatedVendorState state)
    {
        if (state.NextReplenishment is { } arrival)
        {
            var remaining = arrival - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;
            ResupplyStatus.Text = $"New {state.DepartmentName} resupply in {FormatRemaining(remaining)}.";
            ResupplyStatus.ModulateSelfOverride = Color.Gold;
            return;
        }

        ResupplyStatus.Text = state.ReplenishmentPoints > 0
            ? $"{state.ReplenishmentPoints} resupply points available; no funded depleted allocation is queued."
            : "No resupply shipment queued.";
        ResupplyStatus.ModulateSelfOverride = Color.LightGray;
    }

    private static string FormatRemaining(TimeSpan remaining)
    {
        var totalSeconds = Math.Max(0, (int) Math.Ceiling(remaining.TotalSeconds));
        return $"{totalSeconds / 60}:{totalSeconds % 60:00}";
    }

    private Control CreateEntryRow(
        string name,
        string description,
        EntProtoId id,
        string details,
        string? disabledReason,
        string actionText,
        Action onPressed)
    {
        Texture? icon = null;
        if (_prototypes.TryIndex<EntityPrototype>(id, out var entityPrototype))
            icon = _sprites.GetPrototypeIcon(entityPrototype).Default;

        var control = new CMAutomatedVendorEntry();
        control.Configure(icon, name, description, details, disabledReason, actionText, onPressed);
        return control;
    }

    private void AddEmptyMessage(string message)
    {
        Sections.AddChild(new Label
        {
            Text = message,
            Margin = new Thickness(8),
            HorizontalAlignment = HAlignment.Center,
        });
    }

    private List<string> GetAllocationCategories(CMAutomatedVendorState state)
    {
        return state.AllocationCategories
            .Concat(state.Sections.SelectMany(section => section.Entries).Select(entry => entry.Category))
            .Where(category => !string.IsNullOrWhiteSpace(category))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static List<string> GetSharedCategories(CMAutomatedVendorState state)
    {
        return state.SharedEquipmentCategories
            .Concat(state.StoredItems.Select(item => item.Category))
            .Where(category => !string.IsNullOrWhiteSpace(category))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string EnsureCategory(string? selected, IReadOnlyList<string> categories)
    {
        if (selected != null && categories.Contains(selected, StringComparer.OrdinalIgnoreCase))
            return categories.First(category => category.Equals(selected, StringComparison.OrdinalIgnoreCase));

        return categories.FirstOrDefault() ?? "Other";
    }

    private static string WithoutTierPrefix(string text)
    {
        if (!text.StartsWith("Tier ", StringComparison.OrdinalIgnoreCase))
            return text;

        var separator = text.IndexOf(" - ", StringComparison.Ordinal);
        return separator >= 0 ? text[(separator + 3)..] : text;
    }

    private static Button CreateTabButton(string text, bool selected, Action onPressed)
    {
        var button = new Button { Text = text, HorizontalExpand = true };
        if (selected)
            button.ModulateSelfOverride = Color.CornflowerBlue;
        button.OnPressed += _ => onPressed();
        return button;
    }

    private (string Name, string Description) ResolvePrototype(string fallback, EntProtoId id)
    {
        return _prototypes.TryIndex<EntityPrototype>(id, out var prototype)
            ? (prototype.Name, prototype.Description)
            : (fallback, fallback);
    }
}
